-- Criação do banco de dados do Projeto final de banco de dados
-- Alunos: 
-- Igor Laranja Borges Taquary 	18/0122231
-- Marcos Blandim Andrade 		18/0145223

CREATE DATABASE PROJETO_COVID;
USE PROJETO_COVID;
 
DROP TABLE IF EXISTS PAIS;
DROP TABLE IF EXISTS ESTADO;
DROP TABLE IF EXISTS CIDADE;
DROP TABLE IF EXISTS HOSPITAL;
DROP TABLE IF EXISTS LEITO;
DROP TABLE IF EXISTS PACIENTE;
DROP TABLE IF EXISTS VISITA;
DROP TABLE IF EXISTS VISITANTE;
DROP TABLE IF EXISTS DIAGNOSTICO;
DROP TABLE IF EXISTS SINTOMA; 
DROP TABLE IF EXISTS DIAGNOSTICO_SINTOMAS;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS FUNCIONARIO_PARENTES;
DROP TABLE IF EXISTS PARENTE; 

CREATE TABLE PAIS( 
	ID_PAIS		VARCHAR(45) PRIMARY KEY,
	CONTINETE 	VARCHAR(45),
    INFECTADOS	INTEGER UNSIGNED,
    CURADOS		INTEGER UNSIGNED,
    OBITOS		INTEGER UNSIGNED
    );
    
CREATE TABLE ESTADO( 
	UF_ESTADO	VARCHAR(45),
	ID_PAIS		VARCHAR(45) REFERENCES PAIS(ID_PAIS),
    INFECTADOS	INTEGER UNSIGNED,
    CURADOS		INTEGER UNSIGNED,
    OBITOS		INTEGER UNSIGNED,
    PRIMARY KEY (UF_ESTADO, ID_PAIS)
    );

CREATE TABLE CIDADE( 
	ID_CIDADE 	INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NOME		VARCHAR(45) NOT NULL,
	UF_ESTADO	VARCHAR(45) NOT NULL REFERENCES ESTADO(UF_ESTADO),
	ID_PAIS		VARCHAR(45) NOT NULL REFERENCES PAIS(ID_PAIS),
    INFECTADOS	INTEGER UNSIGNED,
    CURADOS		INTEGER UNSIGNED,
    OBITOS		INTEGER UNSIGNED
    );
    
CREATE TABLE HOSPITAL(
	ID_HOSPITAL INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NOME		VARCHAR(45),
	ID_CIDADE 	INTEGER UNSIGNED NOT NULL REFERENCES CIDADE(ID_CIDADE),
	CAPACIDADE	INTEGER UNSIGNED,
	INFECTADOS	INTEGER UNSIGNED,
    CURADOS		INTEGER UNSIGNED,
    OBITOS		INTEGER UNSIGNED
    );
    
CREATE TABLE LEITO(
	NUMERO 		INTEGER UNSIGNED,
	ID_HOSPITAL INTEGER UNSIGNED REFERENCES HOSPITAL(ID_HOSPITAL),
    ANDAR		INTEGER UNSIGNED,
    CAPACIDADE	INTEGER UNSIGNED,
	INTERNADOS	INTEGER UNSIGNED,
    PRIMARY KEY (NUMERO, ID_HOSPITAL)
    );
    
CREATE TABLE PACIENTE(
	CPF			VARCHAR(20) PRIMARY KEY,
    NOME		VARCHAR(65) NOT NULL,
    ESTADO_SAUDE INTEGER UNSIGNED NOT NULL,
    DATA_NASC	DATE,
    DATA_INICIO DATE,
    DATA_FIM 	DATE
    );

CREATE TABLE VISITANTE(
	CPF			VARCHAR(20) PRIMARY KEY,
    NOME		VARCHAR(65) NOT NULL,
    ESTADO_SAUDE INTEGER UNSIGNED NOT NULL,
    DATA_NASC	DATE
    );

CREATE TABLE VISITAS(
	CPF_PACIENTE 	VARCHAR(20) REFERENCES PACIENTE(CPF),
    CPF_VISITANTE 	VARCHAR(20) REFERENCES VISITANTE(CPF),
    DATA_VISITA 	DATE,
    PRIMARY KEY (CPF_PACIENTE, CPF_VISITANTE, DATA_VISITA)
    );
    
CREATE TABLE DIAGNOSTICO(
	CPF_PACIENTE	VARCHAR(20) PRIMARY KEY,
    DATA_DIAGNOSTICO DATE,
    GRAVIDADE		INTEGER UNSIGNED,
    GRUPO_DE_RISCO	INTEGER UNSIGNED,
    METODO_TESTE	INTEGER UNSIGNED
    );

CREATE TABLE SINTOMA(
	ID_SINTOMA		INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME			VARCHAR(45),
    SISTEMA_AFETADO VARCHAR(45),
    GRAVIDADE		INTEGER UNSIGNED,
    NIVEL_CONTAGIO	INTEGER UNSIGNED
    );

CREATE TABLE DIAGNOSTICO_SINTOMAS(
	ID_SINTOMA		INTEGER UNSIGNED REFERENCES SINTOMA(ID_SINTOMA),
	CPF_PACIENTE	VARCHAR(20) REFERENCES DIAGNOSTICO(CPF_PACIENTE),
    PRIMARY KEY (ID_SINTOMA, CPF_PACIENTE)
    );
    
CREATE TABLE FUNCIONARIO(
	MATRICULA		INTEGER UNSIGNED,
	CPF				VARCHAR(20),
    NOME			VARCHAR(45),
    FUNCAO			INTEGER UNSIGNED NOT NULL,
    ESTADO_SAUDE 	INTEGER UNSIGNED NOT NULL,
    DATA_NASC		DATE,
    PRIMARY KEY (CPF, MATRICULA)
    );
	
CREATE TABLE PARENTE(
	CPF			VARCHAR(20) PRIMARY KEY,
    NOME		VARCHAR(65) NOT NULL,
    ESTADO_SAUDE INTEGER UNSIGNED NOT NULL,
    DATA_NASC	DATE
    );
    
CREATE TABLE FUNCIONARIO_PARENTES(
	CPF_FUNC	VARCHAR(20) REFERENCES FUNCIONARIO(CPF),
    CPF_PAR		VARCHAR(20) REFERENCES PARENTE(CPF),
    PRIMARY KEY (CPF_FUNC, CPF_PAR)
    );